apiVersion: v1
kind: ConfigMap
metadata:
  name: procurement-platform-config
  namespace: portfolio
  labels:
    app: procurement-platform
data:
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "480"
